export const dataMember = [
  {
    tier: 5,
    linkUrl: "",
    imageUrl: "",
    name: "Cauli Vilela",
    github: "coquizin",
  },
  {
    tier: 5,
    linkUrl: "",
    imageUrl: "",
    name: "Anderson Freitas",
    github: "andersonFreitas22",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Murilo Cabral",
    github: "acmurilo",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Guilherme Agostinho",
    github: "agostinhogui",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Alessandro Credidio Furlan",
    github: "alessandrofurlan",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Longo",
    github: "Alkoarism",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "AndreAnghinoni",
    github: "AndreAnghinoni",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "André Meneghelli Vale",
    github: "andredalton",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "bruunolc",
    github: "bruunolc",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "caiosilva6001",
    github: "caiosilva6001",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Gabriel Tsutomu",
    github: "CrowleyRanger",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Danielameferreira",
    github: "Danielameferreira",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Enzo Claro",
    github: "EnCl4",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "eoCostaAnderson",
    github: "eoCostaAnderson",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "firme11",
    github: "firme11",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Guilherme Fagundes",
    github: "g-fagundes",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Guilherme de Souza Dourado",
    github: "gdouradoo",
  },
  {
    tier: 5,
    linkUrl: "",
    imageUrl: "",
    name: "GPDA UFABC",
    github: "GPDA-UFABC",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Nicolas Greco",
    github: "grecoww",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "gustavocelso",
    github: "gustavocelso",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Joaodemattos98",
    github: "Joaodemattos98",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Leonardo-Cavalcante",
    github: "Leonardo-Cavalcante",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Lucas Moura de Almeida",
    github: "lucasmouradealmeida",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "lyncoln10",
    github: "lyncoln10",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Rafaella França",
    github: "rafaella-haddad",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "Matheus Alves",
    github: "SirMatthaws",
  },
  {
    tier: 1,
    linkUrl: "",
    imageUrl: "",
    name: "yuriiih",
    github: "yuriiih",
  },
];
